### ISSUE TITLE
Dresden dataset download link not working

### ISSUE THREAD

**Issue by EnricoNapolitan** [bgswaroop/scd-autoencoders#1]
Hello! Very nice work, I am studying it for my degree Thesis in Computer Engineering here in Italy!
I would like to report an issue with the Dresden dataset, in particular the url in the linked dataset is not working (no response from the server), do you know if it is downloadable from another source? Or is it possible for you to upload it somewhere so who is going to use this repo can easily download it?
Thank you in advance

**Comment by JhxxxQ** [comment]
Hello, I have the same problem, does anyone could upload the dresden image dataset?
Thank you!

**Comment by bgswaroop** [comment]
Here is the link to the dataset from my local backup - https://drive.google.com/file/d/1AmIDtImI_Y_-1eUNFfwDyUuEKH9KT6OZ/view?usp=sharing. This link comes without any guarantees of the completeness of the dataset. Unfortunately, this can be verified only by the original authors of the Dresden dataset.

**Comment by bgswaroop** [comment]
Closing this issue since it is beyond the scope of this repository. Added a temporary link to the dataset from my local backup with the prior permission of the authors from the Dresden dataset.
